### ISSUE TITLE
sub0_stim.nii.gz is not a gzip file

### ISSUE THREAD

**Issue by Amysays930** [wtclarke/fsl_mrs_fmrs_demo#1]
Hi, Clarke, I am so interested in the topic of functional MRS, I tried to study the code you shared in the "main_demo.ipynb", but come across some problems. When I load the demo data, It is reported that "sub0_stim.nii.gz is not a gzip file". I also can't open the demo data with FSLeyes. appreciate it if you can give me some tips. details are listed below:

__________________________________________________________________________
from fsl_mrs.utils import mrs_io
# data represents a NIfTI-MRS file in memory
data = mrs_io.read_FID('simulated_data/sub0_stim.nii.gz')
# what's in the data? 
print(data.shape)

---------------------------------------------------------------------------
ImageFileError                            Traceback (most recent call last)
Cell In[9], line 4
      1 from fsl_mrs.utils import mrs_io
      3 # data represents a NIfTI-MRS file in memory
----> 4 data = mrs_io.read_FID('simulated_data/sub0_stim.nii.gz')
      6 # what's in the data? 
      7 print(data.shape)

File ~/.conda/envs/fsl_mrs/lib/python3.8/site-packages/fsl_mrs/utils/mrs_io/main.py:88, in read_FID(filename)
     86     filename = Path(os.readlink(filename))
     87 try:
---> 88     return nifti_mrs.NIFTI_MRS(filename)
     89 except (nifti_mrs.NotNIFTI_MRS, fslpath.PathError):
     90     data_type, id_ext = _check_datatype(Path(filename))

File ~/.conda/envs/fsl_mrs/lib/python3.8/site-packages/fsl_mrs/core/nifti_mrs.py:106, in NIFTI_MRS.__init__(self, *args, **kwargs)
    103     args = list(args)
    104     filename = Path(args[0]).name
--> 106 super().__init__(*args, **kwargs)
    108 # Store original filename for reports etc
    109 self._filename = filename

File ~/.conda/envs/fsl_mrs/lib/python3.8/site-packages/fsl/data/image.py:1238, in Image.__init__(self, image, name, header, xform, loadData, calcRange, threaded, dataSource, loadMeta, dataMgr, **kwargs)
   1236 if isinstance(image, (str, Path)):
   1237     image      = op.abspath(addExt(image))
-> 1238     nibImage   = nib.load(image, **kwargs)
   1239     dataSource = image
   1240     saved      = True

File ~/.conda/envs/fsl_mrs/lib/python3.8/site-packages/nibabel/loadsave.py:105, in load(filename, **kwargs)
    103 matches, msg = _signature_matches_extension(filename, sniff)
    104 if not matches:
--> 105     raise ImageFileError(msg)
    107 raise ImageFileError(f'Cannot work out file type of "{filename}"')

ImageFileError: File /home/rshuang/Amy/test/fsl_mrs_fmrs_demo/simulated_data/sub0_stim.nii.gz is not a gzip file

**Comment by wtclarke** [comment]
Hi,

I think you might need to install git lfs before cloning the repo. See https://git-lfs.github.com/

Will



From: Amysays930 ***@***.***>
Date: Friday, 2 December 2022 at 12:30
To: wtclarke/fsl_mrs_fmrs_demo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wtclarke/fsl_mrs_fmrs_demo] sub0_stim.nii.gz is not a gzip file (Issue #1)

Hi, Clarke, I am so interested in the topic of functional MRS, I tried to study the code you shared in the "main_demo.ipynb", but come across some problems. When I load the demo data, It is reported that "sub0_stim.nii.gz is not a gzip file". I also can't open the demo data with FSLeyes. appreciate it if you can give me some tips. details are listed below:

________________________________

from fsl_mrs.utils import mrs_io

data represents a NIfTI-MRS file in memory

data = mrs_io.read_FID('simulated_data/sub0_stim.nii.gz')

what's in the data?

print(data.shape)

________________________________

ImageFileError Traceback (most recent call last)
Cell In[9], line 4
1 from fsl_mrs.utils import mrs_io
3 # data represents a NIfTI-MRS file in memory
----> 4 data = mrs_io.read_FID('simulated_data/sub0_stim.nii.gz')
6 # what's in the data?
7 print(data.shape)

File ~/.conda/envs/fsl_mrs/lib/python3.8/site-packages/fsl_mrs/utils/mrs_io/main.py:88, in read_FID(filename)
86 filename = Path(os.readlink(filename))
87 try:
---> 88 return nifti_mrs.NIFTI_MRS(filename)
89 except (nifti_mrs.NotNIFTI_MRS, fslpath.PathError):
90 data_type, id_ext = _check_datatype(Path(filename))

File ~/.conda/envs/fsl_mrs/lib/python3.8/site-packages/fsl_mrs/core/nifti_mrs.py:106, in NIFTI_MRS.init(self, *args, **kwargs)
103 args = list(args)
104 filename = Path(args[0]).name
--> 106 super().init(*args, **kwargs)
108 # Store original filename for reports etc
109 self._filename = filename

File ~/.conda/envs/fsl_mrs/lib/python3.8/site-packages/fsl/data/image.py:1238, in Image.init(self, image, name, header, xform, loadData, calcRange, threaded, dataSource, loadMeta, dataMgr, **kwargs)
1236 if isinstance(image, (str, Path)):
1237 image = op.abspath(addExt(image))
-> 1238 nibImage = nib.load(image, **kwargs)
1239 dataSource = image
1240 saved = True

File ~/.conda/envs/fsl_mrs/lib/python3.8/site-packages/nibabel/loadsave.py:105, in load(filename, **kwargs)
103 matches, msg = _signature_matches_extension(filename, sniff)
104 if not matches:
--> 105 raise ImageFileError(msg)
107 raise ImageFileError(f'Cannot work out file type of "{filename}"')

ImageFileError: File /home/rshuang/Amy/test/fsl_mrs_fmrs_demo/simulated_data/sub0_stim.nii.gz is not a gzip file

**Comment by Amysays930** [comment]
Got it . Thanks, Clarke, it has been figured out. I can run the code.
