### ISSUE TITLE
Problem with fsl_dynmrs 

### ISSUE THREAD

**Issue by bkossows** [wtclarke/fsl_mrs_fmrs_demo#2]
Hi William,
I am trying to run fsl_dynmrs command with my data but I get an error message. The same problem appears for a demo data (sub0_stim.nii.gz, design_mat.csv & fmrs_model.py). I've just realized that I haven't used the provided basis set but slaser's basis from Your other repository. I provide the message below and kindly ask for Your support.

`fsl_dynmrs             --data test.nii             --basis ../sLASER_3T_28ms.basis             --dyn_config ./fmrs_model.py             --time_variables ./designmat.csv             --baseline_order 2             --metab_groups Mac             --output ./out             --report             --overwrite
Traceback (most recent call last):
  File "/usr/local/bin/fsl_dynmrs", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fsl_mrs/scripts/fsl_dynmrs.py", line 195, in main
    dyn_res = dyn.fit(init=init, verbose=args.verbose)
  File "/usr/local/lib/python3.7/site-packages/fsl_mrs/dynamic/dynmrs.py", line 262, in fit
    x0 = self.vm.mapped_to_free(init['x'])
  File "/usr/local/lib/python3.7/site-packages/fsl_mrs/dynamic/variable_mapping.py", line 524, in mapped_to_free
    bounds=bounds).x
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 627, in minimize
    **options)
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/tnc.py", line 377, in _minimize_tnc
    bounds=new_bounds)
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 262, in _prepare_scalar_function
    finite_diff_rel_step, bounds, epsilon=epsilon)
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 140, in __init__
    self._update_fun()
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 233, in _update_fun
    self._update_fun_impl()
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in update_fun
    self.f = fun_wrapped(self.x)
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 134, in fun_wrapped
    return fun(np.copy(x), *args)
  File "/usr/local/lib/python3.7/site-packages/fsl_mrs/dynamic/variable_mapping.py", line 508, in loss
    pred = func(x)
TypeError: model_glm() got an unexpected keyword argument 't'`

Environment built with the following Dockerile:
`FROM python:3.7

RUN apt-get update
RUN apt-get install -y git

RUN git clone https://git.fmrib.ox.ac.uk/fsl/fsl_mrs.git
WORKDIR "/fsl_mrs"
RUN pip install .`

**Comment by wtclarke** [comment]
Hi Bartosz,

I came across this the other day I think the partial package think something in a python std library may have changed slightly. In the config file (https://github.com/wtclarke/fsl_mrs_fmrs_demo/blob/main/fmrs_model.py) modify the desmat argument  to match the keyword t.

Will get a fix out for this.

Will

From: Bartosz Kossowski ***@***.***>
Date: Friday, 20 January 2023 at 13:37
To: wtclarke/fsl_mrs_fmrs_demo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wtclarke/fsl_mrs_fmrs_demo] Problem with fsl_dynmrs (Issue #2)

Hi William,
I am trying to run fsl_dynmrs command with my data but I get an error message. The same problem appears for a demo data (sub0_stim.nii.gz, design_mat.csv & fmrs_model.py). I've just realized that I haven't used the provided basis set but slaser's basis from Your other repository. I provide the message below and kindly ask for Your support.

fsl_dynmrs --data test.nii --basis ../sLASER_3T_28ms.basis --dyn_config ./fmrs_model.py --time_variables ./designmat.csv --baseline_order 2 --metab_groups Mac --output ./out --report --overwrite Traceback (most recent call last): File "/usr/local/bin/fsl_dynmrs", line 8, in <module> sys.exit(main()) File "/usr/local/lib/python3.7/site-packages/fsl_mrs/scripts/fsl_dynmrs.py", line 195, in main dyn_res = dyn.fit(init=init, verbose=args.verbose) File "/usr/local/lib/python3.7/site-packages/fsl_mrs/dynamic/dynmrs.py", line 262, in fit x0 = self.vm.mapped_to_free(init['x']) File "/usr/local/lib/python3.7/site-packages/fsl_mrs/dynamic/variable_mapping.py", line 524, in mapped_to_free bounds=bounds).x File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 627, in minimize **options) File "/usr/local/lib/python3.7/site-packages/scipy/optimize/tnc.py", line 377, in _minimize_tnc bounds=new_bounds) File "/usr/local/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 262, in _prepare_scalar_function finite_diff_rel_step, bounds, epsilon=epsilon) File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 140, in __init__ self._update_fun() File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 233, in _update_fun self._update_fun_impl() File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in update_fun self.f = fun_wrapped(self.x) File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 134, in fun_wrapped return fun(np.copy(x), *args) File "/usr/local/lib/python3.7/site-packages/fsl_mrs/dynamic/variable_mapping.py", line 508, in loss pred = func(x) TypeError: model_glm() got an unexpected keyword argument 't'

Environment built with the following Dockerile:
`FROM python:3.7

RUN apt-get update
RUN apt-get install -y git

RUN git clone https://git.fmrib.ox.ac.uk/fsl/fsl_mrs.git
WORKDIR "/fsl_mrs"
RUN pip install .`

**Comment by bkossows** [comment]
Thanks for the quick reply. So did I and it works perfect now.
`def model_glm(p,t):
    return dot(t, p)
def model_glm_grad(p,t):
    return t.T`
